-- MySQL Script generated by MySQL Workbench
-- 05/31/16 20:46:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oop_projekat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oop_projekat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oop_projekat` DEFAULT CHARACTER SET utf8 ;
USE `oop_projekat` ;

-- -----------------------------------------------------
-- Table `oop_projekat`.`korisnik_tip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop_projekat`.`korisnik_tip` (
  `idTip` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(30) NOT NULL,
  `opis` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idTip`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oop_projekat`.`userModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop_projekat`.`userModel` (
  `idUser` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `idTip` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`idUser`, `idTip`),
  INDEX `idTip_idx` (`idTip` ASC),
  UNIQUE INDEX `idKorisnik_UNIQUE` (`idUser` ASC),
  CONSTRAINT `TipKorisnik`
    FOREIGN KEY (`idTip`)
    REFERENCES `oop_projekat`.`korisnik_tip` (`idTip`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oop_projekat`.`workModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop_projekat`.`workModel` (
  `idUser` INT(11) UNSIGNED NOT NULL,
  `workModel` TEXT NOT NULL,
  `quality` DOUBLE NULL DEFAULT NULL,
  `codeAccuracy` DOUBLE NULL DEFAULT NULL,
  `overallImpression` DOUBLE NULL DEFAULT NULL,
  `averageMark` DOUBLE NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  INDEX `idKorisnik_idx` (`idUser` ASC),
  UNIQUE INDEX `idKorisnik_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `rad_UNIQUE` (`workModel` ASC),
  PRIMARY KEY (`idUser`),
  CONSTRAINT `KorisnikRad`
    FOREIGN KEY (`idUser`)
    REFERENCES `oop_projekat`.`userModel` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
